Fixed client muting
ReSpeak/TS3Hook pull request #31
Opened 2018-04-17 19:00 UTC by Najsr

As mentioned in https://github.com/ReSpeak/TS3Hook/pull/18#issuecomment-381760244

2018-04-17 21:51 UTC, Bluscream requested changes
After compiling and trying i only get
```
<23:47:24> Trying to connect to server on XX.XX.XX.XX:XXXX
<23:47:25> undefined error
```
```
[OUT] clientinit client_nickname=bluÛºé client_version=3.?.?\s[Build:\s5680278000] client_platform=Windows                                                                                                                                                                                                                                                                                                                                                                                      
[IN ] error id=1 msg=undefined\serror
```

2018-04-18 09:32 UTC, Najsr commented
Should be ready to merge.

2018-04-18 09:38 UTC, Bluscream commented on TS3Hook/dllmain.cpp
> +			in_str.erase(client_platform + 16, (client_input_muted - client_platform - 17));
That line does cause the `undefined error` for me. The rest works fine

2018-04-18 10:10 UTC, Najsr commented
`[OUT] clientinit client_nickname=Najsr client_version=3.1.7\s[Build:\s1513163251] client_platform=Linux client_input_muted=1 client_output_muted=1 client_input_hardware=1 client_output_hardware=1 client_default_channel client_default_channel_password client_server_password client_meta_data client_version_sign=\/j5TZqPuOU8yMYPdGehvijYvU74KefRrKO5sgTUrkpeslNFiy4XfU7quKW0diLHQoPQn1t3KArdfzOAMk8dlAg== client_key_offset=000 client_nickname_phonetic client_default_token client_badges=Overwolf=0 hwid=XXX`  Works fine for me.

2018-04-18 10:27 UTC, Bluscream commented
@Najsr can you give me a compiled win_x64.dll from you?

2018-04-18 11:22 UTC, Najsr commented
Give it a try now, should be fixed

2018-04-19 00:36 UTC, Bluscream commented
Thanks, i manually merged it in 5866b7e86f9aede3a161d26d879dbd74e4559f70 due to local changes :)

2018-04-19 00:36 UTC, closed without merging